name: Liquibase Test Harness

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  authorize:
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true
      
  liquibase-test-harness:
    needs: authorize
    uses: liquibase/build-logic/.github/workflows/lth-docker.yml@v0.5.7
    secrets: inherit